
    services:
      api_service:
        image: atchee/football-simulator-back-end
        restart: always
        ports:
          - 8081:8081
        networks:
          - springapimysql-net
        environment:
          - spring.datasource.url=jdbc:mysql://mysqldb:3306/football-simulator?createDatabaseIfNotExist=true&characterEncoding=utf8
          - spring.datasource.username=root
          - spring.datasource.password=
          - security.jwt.secret-key=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
        depends_on:
          - mysqldb
        volumes:
          - ~/.gradle:/home/gradle/.gradle  # Cache Gradle dependencies

      mysqldb:
        image: "mysql:8.0"
        restart: always
        ports:
          - 3306:3306
        networks:
          - springapimysql-net
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD=true
          - MYSQL_DATABASE=football-simulator

      phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
          - 8083:8083
        networks:
          - springapimysql-net
        environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=mysqldb
          - PMA_USER=root
          - PMA_PASSWORD=
          - PMA_ABSOLUTE_URI=http://localhost/
          - PMA_CONFIG='/etc/phpmyadmin/config.user.inc.php'
        depends_on:
          - mysqldb
        volumes:
          - ./config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

    networks:
      springapimysql-net:
